import pandas as pd

df = pd.read_csv(r"data\survey_results_public.csv")
df_schema = pd.read_csv(r"data\survey_results_schema.csv")
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)
# print(df.head())
# print(df_schema)
print(df.shape)
# print(df.columns)
# print(df.loc[[1, 2, 3, 4, 5, 8000], "Hobbyist"])
# print(df['Hobbyist'])
# print(df['Hobbyist'].value_counts())
# print(df.loc[0])
# print(df.loc[0, 'Hobbyist'])
# print(df.loc[1, 'Hobbyist'])
# print(df.loc[[0, 1, 2], 'Hobbyist'])
# print(df.loc[0:2, 'Hobbyist'])
# print(df.loc[0:20:2, 'Hobbyist'])
# print(df.loc[0:20:2, 'Hobbyist':'Employment'])
